name: ana-ds
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy
  - matplotlib
  - pyarrow
  - db-dtypes
  - google-cloud-bigquery
  - google-cloud-bigquery-storage
  - google-cloud-storage
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - jupysql
      - duckdb
